rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text
issue_title,301,idan,oauthlib,pyworkshop,2014-11-27 14:49:07,"CODE:
auth_url = self.prepare_request_uri(  
        authorization_url, redirect_uri=**self.redirect_uri**,
        scope=self.scope, state=self.state, **kwargs)     

SHOULD BE **self.redirect_url**
",start issue,Error on Client.prepare_authorization_request,code authurl selfpreparerequesturi authorizationurl redirecturiselfredirecturi scopeselfscop stateselfst kwarg should BE selfredirecturl
issue_comment,301,idan,oauthlib,JonnyFunFun,2015-02-27 14:19:50,"I encountered the same issue, as well as in `prepare_refresh_token_request`:

Around line 300:

```
body = self._client.prepare_refresh_body(body=body,
                refresh_token=refresh_token, scope=self.scope, **kwargs)
```

However there is no `_client` attribute.  I submitted a pull request with the change in #324 but it appears that all tests fail after this, so I'm not sure what to do with it.
",,,I encount issu well around line 300 howev attribut I submit pull request chang 324 appear test fail Im sure
