rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text
issue_title,380,idan,oauthlib,coreycb,2015-08-12 14:58:53,"This is on version oauthlib 1.0.0.

Traceback (most recent call last):
  File ""keystoneclient/tests/unit/v3/test_oauth1.py"", line 235, in test_create_access_token_expires_at
    oauth_client)
  File ""keystoneclient/tests/unit/v3/test_oauth1.py"", line 112, in _validate_oauth_headers
    header_params = oauth_client.get_oauth_params(None)
  File ""/usr/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/__init__.py"", line 181, in get_oauth_params
    content_type = request.headers.get('Content-Type', None)
AttributeError: 'NoneType' object has no attribute 'headers'

Should get_oauth_params() be checking if request is None or is that a user error?
",start issue,AttributeError: 'NoneType' object has no attribute 'headers',thi version oauthlib 100 traceback recent call last file keystoneclienttestsunitv3testoauth1pi line 235 testcreateaccesstokenexpiresat oauthclient file keystoneclienttestsunitv3testoauth1pi line 112 validateoauthhead headerparam oauthclientgetoauthparamsnon file usrlibpython27distpackagesoauthliboauth1rfc5849initpi line 181 getoauthparam contenttyp requestheadersgetcontenttyp none attributeerror nonetyp object attribut header should getoauthparam check request none user error
issue_closed,380,idan,oauthlib,coreycb,2015-08-12 19:39:38,,closed issue,AttributeError: 'NoneType' object has no attribute 'headers',
issue_comment,380,idan,oauthlib,jvanasco,2015-08-12 17:36:17,"That looks like a user error to me.  `get_oauth_params` specifies 1 argument -- a request -- and you're explicitly sending in `None`.
",,,that look like user error specifi 1 argument request your explicitli send
issue_comment,380,idan,oauthlib,coreycb,2015-08-12 17:45:41,"Fair enough, thanks for looking.
",,,fair enough thank look
