rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text,Test
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text,N
issue_title,337,idan,oauthlib,lribinik,2015-04-20 12:46:14,"fixing self.redirect_uri to self.redirect_url since self.redirect_uri doesn't exist
",start issue,fix typo in base.py:prepare_authorization_request,fix selfredirecturi selfredirecturl sinc selfredirecturi doesnt exist,N
issue_closed,337,idan,oauthlib,thedrow,2015-07-01 11:33:29,nan,closed issue,fix typo in base.py:prepare_authorization_request,nan,N
pull_request_title,337,idan,oauthlib,lribinik,2015-04-20 12:46:14,"fixing self.redirect_uri to self.redirect_url since self.redirect_uri doesn't exist
",95f012023a0a6919eeac31903992d8b9df087484,fix typo in base.py:prepare_authorization_request,fix selfredirecturi selfredirecturl sinc selfredirecturi doesnt exist,N
issue_comment,337,idan,oauthlib,josephtate,2015-05-06 21:14:13,"Seems like we're missing test coverage for this. Any chance you can add one?
",nan,nan,seem like miss test coverag ani chanc add one,Y
issue_comment,337,idan,oauthlib,lribinik,2015-05-13 09:59:02,"Will work on adding a test.
",nan,nan,will work ad test,Y
issue_comment,337,idan,oauthlib,thedrow,2015-07-01 11:33:29,"Already merged with a test in #351. Thanks.
",nan,nan,alreadi merg test 351 thank,Y
issue_comment,337,idan,oauthlib,lribinik,2015-07-01 14:17:14,"Thanks! (Unfortunately wasn't able to get to it)
",nan,nan,thank unfortun wasnt abl get,N
pull_request_commit,337,idan,oauthlib,leon.ribinik@convertro.com,2015-04-20 12:41:17,fixing self.redirect_ui to self.redirect_url since self.redirect_uri doesn't exist,95f012023a0a6919eeac31903992d8b9df087484,nan,fix selfredirectui selfredirecturl sinc selfredirecturi doesnt exist,N
